src/Entity/Availability.php
<?php

namespace App\Entity;

use App\Repository\AvailabilityRepository;
use Doctrine\ORM\Mapping as ORM;
use JetBrains\PhpStorm\Pure;

/**
 * @ORM\Entity(repositoryClass=AvailabilityRepository::class)
 */
class Availability
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="availabilities")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $ProductSize;

    /**
     * @ORM\Column(type="smallint")
     */
    private $quantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getProductSize(): ?string
    {
        return $this->ProductSize;
    }

    public function setProductSize(string $ProductSize): self
    {
        $this->ProductSize = $ProductSize;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * @return string
     */
    #[Pure] public function __toString(): string
    {
        return $this->getProductSize();
    }


}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Availability;
use App\Entity\Cart;
use App\Entity\CartProduct;
use App\Entity\Comment;
use App\Entity\Image;
use App\Entity\Product;
use App\Entity\ProductEdit;
use App\Entity\ProductImageEdit;
use App\Entity\ProductImages;
use App\Entity\ProductSearch;
use App\Entity\ProductSize;
use App\Entity\Shop;
use App\Form\AvailabilityType;
use App\Form\CartFormType;
use App\Form\CommentFormType;
use App\Form\ImageEditFormType;
use App\Form\ImageFormType;
use App\Form\ProductEditFormType;
use App\Form\ProductFormType;
use App\Form\ProductSearchFormType;
use App\Repository\CartRepository;
use App\Repository\ProductRepository;
use App\Repository\StockRepository;
use App\Services\FileUploader;
use App\Services\ConnectedUserService;
use Doctrine\ORM\EntityManagerInterface;
use JetBrains\PhpStorm\Pure;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Notifier\Notification\Notification;
use Symfony\Component\Notifier\NotifierInterface;
use Symfony\Component\Routing\Annotation\Route;

class ProductController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    /**
     * ProductController constructor.
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @param Request $request
     * @param FileUploader $fileUploader
     * @param Shop $shop
     * @return Response
     * @IsGranted("ROLE_MERCHANT")
     */
    #[Route('/product/new_product/shop_ref={shop}-{slug}', name: 'new_product')]
    public function newProduct(Request $request, FileUploader $fileUploader, Shop $shop): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductFormType::class, $product);
        $form->handleRequest($request);
        if($form->isSubmitted() and $form->isValid()){
            $product->setCreatedAt(new \DateTimeImmutable('now'))
                ->setShop($shop);
            if($images = $form['productImages']->getData()){
                $fileUploader->uploadProductImages($images, $product);
            }
            $productSizes = $form['productSizes']->getData();
            $this->addSizeToProduct($productSizes, $product);
            $product->setNbSize(count($product->getProductSizes()))
                ->setProductState(false);
            $this->entityManager->persist($product);
            $this->entityManager->flush();
            return $this->redirectToRoute('new_quantity', [
                'shop'=>$shop->getId(),
                'product'=>$product->getId(),
                'sizeState'=>true
            ]);
        }
        return $this->render('product/new_product.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @param Product $product
     * @param Shop $shop
     * @param bool $sizeState
     * @return Response
     */
    #[Route('/product/add_new_quantity/{shop}-new-quantity-{product}-{sizeState}', name: 'new_quantity')]
    public function addProductSizeQuantity(Product $product, Shop $shop, string $sizeState):Response{
        return $this->render('/product/add_quantity.html.twig', [
            'shop'=>$shop,
            'product'=>$product,
            'sold_out'=>$sizeState
        ]);
    }

    /**
     * @param Shop $shop
     * @param Product $product
     * @param int $sizeIndex
     * @param StockRepository $repository
     * @return Response
     */
    #[Route('/product/is_in_stock/{shop}/{product}/{sizeIndex}', name: 'is_in_stock')]
    public function isInStock(Shop $shop, Product $product, int $sizeIndex, StockRepository $repository):Response{
        $stock = $shop->getStocks()[0];
        $stockItem = $stock->isInStock($shop, $product->getProductSizes()[$sizeIndex], $product->getProductType(),
            $product->getProductCategory(), $product->getProductBrand(), $repository);
        if($stockItem)
            return $this->redirectToRoute('availability', [
                'product'=>$product->getId(),
                'shop'=>$shop->getId(),
                'sizeIndex'=>$sizeIndex,
                'sizeState'=>"new"
            ]);
        return $this->redirectToRoute('new_quantity', [
            'shop'=>$shop->getId(),
            'product'=>$product->getId(),
            'sizeState'=>"out"
        ]);
    }

    /**
     * @param Shop $shop
     * @param Request $request
     * @param Product $product
     * @param int $sizeIndex
     * @param StockRepository $repository
     * @return Response
     */
    #[Route('/product/new-product/availability/{product}-shop_ref={shop}-{sizeIndex}', name: 'availability')]
    public function availability(Shop $shop, Request $request, Product $product, int $sizeIndex, StockRepository $repository):Response{
        $availability = new Availability();
        $form = $this->createForm(AvailabilityType::class, $availability);
        $form->handleRequest($request);
        if($form->isSubmitted() and $form->isValid()){
            if($product->getNbSize() > 0) {
                $product->setNbSize($product->getNbSize()-1);
                $availability->setProductSize($product->getProductSizes()[$sizeIndex]);
                $availability->setProduct($product);
                $product->setProductState(true);
                $stockItem = $repository->findOneBy(['shop'=>$shop->getId(), 'type'=>$product->getProductType(),
                    'size'=>$availability->getProductSize(), 'category'=>$product->getProductCategory(), 'brand'=>$product->getProductBrand()]);
                $stockItem->setQuantity($stockItem->getQuantity() - $availability->getQuantity());
                $this->entityManager->persist($availability);
                $this->entityManager->flush();
                if($product->getNbSize()==0)
                    return $this->redirectToRoute('products', [
                        'shop'=>$shop->getId()
                    ]);
                return $this->redirectToRoute('new_quantity', [
                    'shop'=>$shop->getId(),
                    'product'=>$product->getId(),
                    'sizeState'=>'out'
                ]);
            }
        }
        return $this->render('/product/product_availability.html.twig', [
            'form'=>$form->createView(),
            'product'=>$product,
            'shop'=>$shop,
        ]);
    }
    /**
     * @param array $sizes
     * @param Product $product
     */
    private function addSizeToProduct(array $sizes, Product $product):void{
        foreach ($sizes as $size){
            $newSize = new ProductSize();
            $newSize->setSize($size);
            $product->addProductSize($newSize);
        }
    }

    /**
     * @param Product $product
     * @param Request $request
     * @param NotifierInterface $notifier
     * @param Shop $shop
     * @return Response
     * @IsGranted("ROLE_MERCHANT")
     */
    #[Route('/product/edit_product/shop_ref={shop}-edit-{product}', name: "edit_product")]
    public function editProduct(Product $product, Request $request, NotifierInterface $notifier, Shop $shop):Response{
        $edit = new ProductEdit();
        $form = $this->createForm(ProductEditFormType::class, $edit);
        $form->handleRequest($request);

        if($form->isSubmitted() and $form->isValid()){
            $edit->setCreatedAt(new \DateTimeImmutable('now'));
            $product->setProductBrand($edit->getProductBrand())
                ->setProductCategory($edit->getProductCategory())
                ->setProductName($edit->getProductName())
                ->setProductPrice($edit->getProductPrice())
                ->setCreatedAt($edit->getCreatedAt());

            $this->entityManager->flush();
            $notifier->send(new Notification("Modification avec succès !", ['browser']));
            return $this->redirectToRoute('products', [
                'shop'=>$shop->getId()
            ]);
        }
        return $this->render('product/edit_product.html.twig', [
            'form'=>$form->createView()
        ]);
    }

    /**
     * @param Product $product
     * @param Request $request
     * @param NotifierInterface $notifier
     * @param FileUploader $fileUploader
     * @return Response
     * @IsGranted("ROLE_MERCHANT")
     */
    #[Route('/product/image_edit/image-product_ref={product}', name: 'product_image')]
    public function editImages(Product $product, Request $request, NotifierInterface $notifier, FileUploader $fileUploader):Response{
        $newImages = new ProductImageEdit();
        $form = $this->createForm(ImageEditFormType::class, $newImages);
        $form->handleRequest($request);
        if($form->isSubmitted() and $form->isValid()){
            if($images = $form['filename']->getData()){
                $fileUploader->uploadProductImages($images, $product);
            }
            $this->entityManager->flush();
            $notifier->send(new Notification("Modification avec succès !", ['browser']));
            return $this->redirectToRoute('product_image', [
                'product'=>$product->getId()
            ]);
        }
        return $this->render('product/product_image.html.twig', [
            'form'=>$form->createView(),
            'product'=>$product
        ]);
    }

    /**
     * @param Product $product
     * @param Request $request
     * @param NotifierInterface $notifier
     * @param FileUploader $fileUploader
     * @param Shop $shop
     * @return Response|null
     */
    #[Route('/product/delete_product/delete-product-{product}-{shop}', name: 'delete_product')]

templates/product/__add_to_cart_form.html.twig
{{ form_start(formCart) }}
<div class="__row-2">
    <div class="__column">
        {{ form_label(formCart.productSize, '* La taille') }}
        {{ form_widget(formCart.productSize) }}
    </div>
    <div class="__column">
        {{ form_label(formCart.productQuantity, '* La quantité') }}
        {{ form_widget(formCart.productQuantity) }}
    </div>
</div>

<div class="__row-1">
    <div class="__column_btn">
        {% if product.availabilities|length %}
            <button class="btn validate_btn" type="submit"><i class="fas fa-cart-plus"></i></button>
            {% else %}
                <button class="btn validate_btn" type="button"><i class="fas fa-cart-plus"></i></button>
        {% endif %}
    </div>
</div>
{{ form_end(formCart) }}

templates/product/__edit_product.html.twig
{{ form_start(form) }}
<p>Modification</p>
<hr>
<div class="__row-2">
    <div class="__column">
        {{ form_label(form.productName, "* Nouveau nom") }}
        {{ form_widget(form.productName) }}
    </div>
    <div class="__column">
        {{ form_label(form.productGender, "* Selectionnez le genre") }}
        {{ form_widget(form.productGender) }}
    </div>
</div>
<div class="__row-3">
    <div class="__column">
        {{ form_label(form.productCategory, "* Selectionnez la catégorie") }}
        {{ form_widget(form.productCategory) }}
    </div>
    <div class="__column">
        {{ form_label(form.productType, "* Selectionnez le type") }}
        {{ form_widget(form.productType) }}
    </div>
    <div class="__column">
        {{ form_label(form.productBrand, "* Selectionnez la marque") }}
        {{ form_widget(form.productBrand) }}
    </div>
</div>
<div class="__row-1">
    <div class="__column">
        {{ form_label(form.productPrice, "* Nouveau prix du produit") }}
        {{ form_widget(form.productPrice) }}
    </div>
</div>
<div class="__row-1">
    <div class="__column_btn">
        <button class="btn btn-sm validate_btn" type="submit">Valider</button>
    </div>
</div>
{{ form_end(form) }}

templates/product/__new_product.html.twig
{{ form_start(form) }}
<p>Ajout de nouveau produit</p>
<hr>
<div class="__row-1">
    <div class="__column">
        {{ form_label(form.productName, "* Nom du produit") }}
        {{ form_widget(form.productName) }}
    </div>
</div>
<div class="__row-3">
    <div class="__column">
        {{ form_label(form.productCategory, "* Selectionnez la catégorie") }}
        {{ form_widget(form.productCategory) }}
    </div>
    <div class="__column">
        {{ form_label(form.productType, "* Selectionnez le type") }}
        {{ form_widget(form.productType) }}
    </div>
    <div class="__column">
        {{ form_label(form.productBrand, "* Selectionnez la marque") }}
        {{ form_widget(form.productBrand) }}
    </div>
</div>
<div class="__row-2">
    <div class="__column">
        {{ form_label(form.productSizes, "* Selectionnez les tailles") }}
        {{ form_widget(form.productSizes) }}
    </div>
    <div class="__column">
        {{ form_label(form.productPrice, "* Le prix du produit") }}
        {{ form_widget(form.productPrice) }}
    </div>
</div>
<div class="__row-1">
    <div class="__column">
        {{ form_label(form.productImages, "* Chargez les images") }}
        {{ form_widget(form.productImages) }}
    </div>
</div>
<div class="__row-1">
    <div class="__column_btn">
        <button class="btn btn-sm validate_btn" type="submit">Suivant</button>
    </div>
</div>
{{ form_end(form) }}

templates/product/__new_product_image.html.twig
{{ form_start(form) }}
<div class="__row-1">
    <div class="__column">
        {{ form_label(form.filename, "* Nouvelles images") }}
        {{ form_widget(form.filename) }}
    </div>
    <div class="__row-1">
        <div class="__column_btn">
            <button class="btn validate_btn" type="submit">Valider</button>
        </div>
    </div>
</div>
{{ form_end(form) }}

templates/product/__product_card.html.twig
<div class="__product_card">
    <div class="__shop_product_image">
        <a href="{{ path('product_details', {
            product:product.id,
            slug: product.getSlug(),
            shop: product.shop.getId()
        }) }}" class="__image_product">
            <img src="{{ asset('images/products_image/'~product.getProductImages()[0].getFilename()) }}" alt="product image">
        </a>
    </div>
    <div class="__product_body">
        <div class="__product_infos">
            <span class="__product_brand">{{ product.productBrand }}</span>
            <span>{{ product.productName }} </span>
            <h5 class="__product_price">{{ product.productPrice | number_format(0, ' ', ' ') }} FG</h5>
        </div>
        <ul class="list-unstyled">
            {% for size in product.productSizes %}
                <li>{{ size.getSize() }}</li>
            {% endfor %}
        </ul>
        {% if not product.productState %}
            <span class="badge badge-danger">Non disponible</span>
        {% endif %}
    </div>
</div>

templates/product/__product_card_command.html.twig
<div class="__product_card">
    <div class="__shop_product_image">
        <a href="{{ path('product_details', {
            product:product.id,
            slug: product.getSlug(),
            shop: product.shop.getId()
        }) }}" class="__image_product">
            <img src="{{ asset('images/products_image/'~product.getProductImages()[0].getFilename()) }}" alt="product image">
        </a>
    </div>
    <div class="__product_body">
        <div class="__product_infos">
            <span class="__product_brand">{{ product.productBrand }} {{ cart.productSize }} <em>x{{ cart.productQuantity }}</em></span>
            <span>{{ product.productName }} <span class="__product_price">{{ (product.productPrice*cart.productQuantity) | number_format(0, ' ', ' ') }} FG </span></span>
        </div>
    </div>
</div>

templates/product/__product_card_shop.html.twig
<div class="__product_card">
    <div class="__product_image">
        <img src="{{ asset('images/products_image/'~product.getProductImages()[0].getFilename()) }}" alt="product image">
        <a href="{{ path('product_image', { product:product.id }) }}" class="__images_edit">
            <i class="fas fa-images"></i>
            {{ product.getProductImages()|length }}
        </a>
    </div>
    <div class="__product_body">
        <div class="__product_infos">
            <span class="__product_brand">{{ product.productBrand }}</span>
            <span>{{ product.productName }} <span class="__product_price">{{ product.productPrice | number_format(0, ' ', ' ') }} FG </span></span>
        </div>
        <hr>
        <a href="{{ path('edit_product', { shop:product.shop.id, product:product.id }) }}" class="btn btn-sm"><i class="far fa-edit"></i></a>
        <form method="post" onsubmit="return confirm('Êtes-vous sûr ?')" action="{{ path('delete_product', { product:product.id, shop:product.shop.id }) }}" style="display: inline-block;">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token('delete'~product.getId()) }}">
            <button type="submit" class="btn btn-sm"><i class="fas fas fa-trash-alt"></i></button>
        </form>
        <a href="" class="btn btn-sm">Voire en rayon</a>
        {% if product.nbSize != 0 %}
            <a href="{{ path('new_quantity', {
                product:product.id,
                shop:product.shop.id,
                sizeState:"new"
            }) }}" class="btn btn-sm">Ajouter en rayon</a>
        {% endif %}
    </div>
</div>

templates/product/__related_product.html.twig
<div class="__related_product_card">
    <div class="__shop_product_image">
        <a href="{{ path('product_details', {
            product:product.id,
            slug: product.getSlug(),
            shop: product.shop.getId()
        }) }}" class="__image_product">
            <img src="{{ asset('images/products_image/'~product.getProductImages()[0].getFilename()) }}" alt="product image">
        </a>
    </div>
    <div class="__product_body">
        <div class="__product_infos">
            <span class="__product_brand">{{ product.productBrand }}</span>
            <span>{{ product.productName }} </span>
            <h6 class="__product_price">{{ product.productPrice | number_format(0, ' ', ' ') }} FG</h6>
        </div>
    </div>
</div>

templates/product/__search_product_form.html.twig
{{ form_start(form) }}
{{ form_widget(form.keyWord) }}
<button class="btn validate_btn" type="submit"><i class="fas fa-search"></i></button>
{{ form_end(form) }}

templates/product/add_quantity.html.twig
{% extends 'back_shop_base.html.twig' %}
{% block title %}Nombre d'exemplaire de produit par taille{% endblock %}

{% block body %}
    <main class="__back_shop_container">
        <main class="__back_shop_page">
            <div class="__container">
                <p>Pour chacune des tailles, indiquez le nombre d'exemplaires du produit : {{ product.slug }}</p>
                <div class="__sizes">
                    {% for size in product.getTheSizesNotAdded() %}
                        <a href="{{ path('is_in_stock', {
                            product:product.id,
                            sizeIndex: product.productSizes.indexOf(size),
                            shop:shop.id
                        }) }}">{{ size.size }}
                        </a>
                    {% endfor %}
                </div>
                {% if sold_out is same as("out")%}
                    <p class="badge badge-danger mt-2">Le produit n'est pas disponible dans cette taille</p>
                {% endif %}
            </div>
        </main>
    </main>
{% endblock %}

templates/product/new_product.html.twig
{% extends 'back_shop_base.html.twig' %}

{% block title %}Nouveau produit{% endblock %}

{% block body %}
    <main class="__back_shop_container">
        <main class="__back_shop_page">
            <div class="__form_container">
                {% include 'product/__new_product.html.twig' %}
                <p>
                    La selection de la taille permet d'en choisir plusieurs.
                    Et pour chaque taille, il faut ajouter la quantité sur la page suivante. <br>
                    <em>Exemple :</em> <br>
                    Pour un jeans en taille de 32-34, 36-38, 40-42, ... <br>
                    Racourcis selection multiple: sur le clavier : <br>
                    button CTRL+clic droit souris ou <br>
                    button SHIFT+flèche du bas
                </p>
            </div>
        </main>
    </main>
{% endblock %}

templates/product/product_availability.html.twig
{% extends 'back_shop_base.html.twig' %}

{% block title %}Nouveau produit{% endblock %}

{% block body %}
    <main class="__back_shop_container">
        <main class="__back_shop_page">
            <div class="__form_container">
                <p>Pour chacune des tailles, indiquez le nombre d'exemplaires du produit</p>
                {% include 'product/__availability_form_type.html.twig' %}
            </div>
        </main>
    </main>
{% endblock %}

templates/product/product_details.html.twig
{% extends 'the_shop_base.html.twig' %}
{% block title %}{{ product.getSlug() }}{% endblock %}

{% block body %}
    <main class="__product_details_main_page">
        <main class="__product_details_container">

            <div class="__product_details">
                <p class="shop_infos"></p>
                <div class="__product_search">
                    {% include "product/__search_product_form.html.twig" %}
                </div>
                <hr>
                <div class="__the_shop_cat">
                    <ul class="list-unstyled">
                        <li><a href="{{ path('product_by_cat', {
                                shop:theShop.id,
                                category:'ACCESSOIRES'
                            }) }}">ACCESSOIRES</a></li>
                        <li><a href="{{ path('product_by_cat', {
                                shop:theShop.id,
                                category:'CHAUSSURES'
                            }) }}">CHAUSSURES</a></li>
                        <li><a href="{{ path('product_by_cat', {
                                shop:theShop.id,
                                category:'VETEMENTS'
                            }) }}">VÊTEMENTS</a></li>
                    </ul>
                </div>

                <div class="__images" data-nb_img="{{ product.productImages | length }}" id="images">
                    {% for img in product.productImages %}
                        <div class="__product_img_item">
                            <img src="{{ asset('images/products_image/'~img.getFilename()) }}" alt="">
                        </div>
                    {% endfor %}
                    <a class="__left" id="__left">&#10094;</a>
                    <a class="__right" id="__right">&#10095;</a>
                    <div class="__dot_control">
                        {% for image in product.productImages %}
                            <span class="dot" data-index="{{ loop.index }}"></span>
                        {% endfor %}
                    </div>
                </div>
                <div class="__infos">
                    <p>{{ product.productBrand }}</p>
                    <h3>{{ product.productName  }}</h3>
                    <span class="price">Prix : </span><span class="badge badge-danger">{{ product.productPrice|number_format(0, ' ', ' ') }} FG</span>
                    <hr>
                    <p>Pour ajouter cet article dans votre panier, veillez selectionner la taille</p>
                    <div class="__add_to_cart">
                        {% include "product/__add_to_cart_form.html.twig" %}
                    </div>
                    {% for message in app.flashes('notification') %}
                        <div class="alert-danger __alert_error p-3" style="display: flex;">
                            <p>{{ message }} <i class="far fa-surprise"></i></p>
                        </div>
                    {% endfor %}
                </div>
                <hr>
                <h4>Les clients aiment aussi ceux-ci</h4>
                <div class="__related_product">
                    {% for product in relatedProducts %}
                        {% include "product/__related_product.html.twig" with {"product": product} %}
                    {% endfor %}
                </div>
            </div>
        </main>
    </main>
{% endblock %}

templates/product/product_image.html.twig
{% extends 'back_shop_base.html.twig' %}
{% block title %}Image-{{ product.getSlug() }}{% endblock %}

{% block body %}
    <main class="__back_shop_container">
        <main class="__back_shop_page">
            <div class="__product_images_container" id="product">
                {% for image in product.productImages %}
                    <div class="__product_image">
                        <img src="{{ asset('/images/products_image/'~image.filename) }}" alt="product image">
                        <button class="btn delete_btn" id="image-{{ image.id }}" data-url="{{ path('delete_product_image', {
                            product:product.id,
                            image:image.id
                        }) }}"><i class="far fa-trash-alt"></i></button>
                    </div>
                {% endfor %}
                {% include 'product/__new_product_image.html.twig' %}
            </div>
        </main>
    </main>
    {% block javascripts %}
        {{ encore_entry_script_tags('delete_product_image') }}
    {% endblock %}
{% endblock %}